use crate::common;
use std::fs::File;
use std::io::{self, prelude::*, BufReader};

/// Write a 2D array of allele frequencies to a file, one `|`-joined line per site.
fn write_allele_freqs(counts: Vec<Vec<f32>>, output_file: &str) -> io::Result<()> {
    let mut output_str = Vec::new();
    for one_site in &counts {
        let one_site_str = one_site
            .iter()
            .map(|num| num.to_string())
            .collect::<Vec<String>>()
            .join("|");
        output_str.push(one_site_str);
    }
    common::write_strings(output_str, output_file)
}

/// Convert a 2D array of strings to u32, failing on any unparseable entry.
/// Counts files are machine-generated by `count`, so a non-numeric token
/// means the file is wrong; silently treating it as 0 would corrupt the
/// frequency estimates.
fn vec_vec_string_to_vec_vec_u32(
    string_vec_vec: Vec<Vec<String>>,
) -> Result<Vec<Vec<u32>>, io::Error> {
    let mut result = Vec::new();
    for (row_index, inner_vec_strings) in string_vec_vec.into_iter().enumerate() {
        let mut inner = Vec::with_capacity(inner_vec_strings.len());
        for (allele_index, s) in inner_vec_strings.into_iter().enumerate() {
            match s.trim().parse::<u32>() {
                Ok(value) => inner.push(value),
                Err(_) => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!(
                            "Invalid count '{}' at line {}, allele {} (expected a non-negative integer)",
                            s,
                            row_index + 1,
                            allele_index
                        ),
                    ));
                }
            }
        }
        result.push(inner);
    }
    Ok(result)
}

/// Divide two 2D arrays elementwise, returning NaN where the divisor is zero.
/// Shape mismatches between the counts table and the index mean the inputs
/// are inconsistent, so they are errors, not truncations.
fn elementwise_division_2d(
    vec_a: &[Vec<u32>],
    vec_b: &[Vec<u32>],
) -> Result<Vec<Vec<f32>>, io::Error> {
    if vec_a.len() != vec_b.len() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "Counts table has {} lines but index has {} entries",
                vec_a.len(),
                vec_b.len()
            ),
        ));
    }

    let result: Vec<Vec<f32>> = vec_a
        .iter()
        .zip(vec_b.iter())
        .enumerate()
        .map(|(line_index, (inner_a, inner_b))| {
            if inner_a.len() != inner_b.len() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!(
                        "Line {} has {} allele counts but index has {} alleles",
                        line_index + 1,
                        inner_a.len(),
                        inner_b.len()
                    ),
                ));
            }
            Ok(inner_a
                .iter()
                .zip(inner_b.iter())
                .map(|(&a, &b)| {
                    if b == 0 {
                        log::warn!("Division by zero detected because there are zero allele-specific k-mers for a particular variant (frequency estimate will be NaN).");
                        f32::NAN
                    } else {
                        (a as f32)/(b as f32)
                    }
                })
                .collect())
        })
        .collect::<Result<Vec<_>, io::Error>>()?;

    Ok(result)
}

/// Normalize each row of counts by its sum to get allele frequencies.
fn normalized_counts_to_allele_freq(norm_counts: Vec<Vec<f32>>) -> Vec<Vec<f32>> {
    let mut sums: Vec<f32> = Vec::new();
    for inner_vec in &norm_counts {
        sums.push(inner_vec.iter().sum());
    }
    let mut result = Vec::new();
    for (norm_count, sum) in norm_counts.iter().zip(sums.iter()) {
        let mut allele_freqs = Vec::new();
        for count in norm_count {
            allele_freqs.push(count / sum)
        }
        result.push(allele_freqs);
    }
    result
}

/// Convert counts by allele into allele frequencies and write them to a file.
pub fn call_from_counts(index: &str, counts: &str, output: &str) -> Result<(), io::Error> {
    log::info!("Reading index for number of unique k-mers per allele...");
    let num_uniq_kmers_per_allele = common::read_index_field(index, 6)?;
    if num_uniq_kmers_per_allele.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "Index '{}' yielded no entries; is it a freqk index file?",
                index
            ),
        ));
    }
    log::info!("Converting data to u32...");
    let num_uniq_kmers_per_allele_u32 = vec_vec_string_to_vec_vec_u32(num_uniq_kmers_per_allele)?;
    log::info!("Parsing counts by allele...");
    let file = File::open(counts)?;
    let reader = BufReader::new(file);
    let mut kmer_counts_per_allele = Vec::new();
    for line_result in reader.lines() {
        let line = line_result?;
        let fields: Vec<String> = line.split('|').map(|s| s.to_owned()).collect();
        log::debug!("Parsed counts by allele: {:?}", fields);
        kmer_counts_per_allele.push(fields);
    }
    if kmer_counts_per_allele.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "Counts file '{}' is empty; expected one '|'-separated line per index entry",
                counts
            ),
        ));
    }
    log::info!("Converting data to u32...");
    let kmer_counts_per_allele_u32 = vec_vec_string_to_vec_vec_u32(kmer_counts_per_allele)?;
    log::info!("Normalizing k-mer counts by number of allele-specific k-mers...");
    let counts_per_kmer =
        elementwise_division_2d(&kmer_counts_per_allele_u32, &num_uniq_kmers_per_allele_u32)?;
    log::info!("Converting normalized counts to allele frequencies...");
    let allele_freq = normalized_counts_to_allele_freq(counts_per_kmer);
    log::info!("Writing allele frequency estimates to {}", output);
    write_allele_freqs(allele_freq, output)
}

#[cfg(test)]
mod unit_tests {
    use super::*;

    #[test]
    fn test_elementwise_division_2d() {
        let test_kmer_counts_per_allele = vec![vec![55, 11], vec![22, 10]];
        let test_num_uniq_kmers_per_allele = vec![vec![10, 4], vec![2, 20]];
        let expected = vec![vec![5.5, 2.75], vec![11.0, 0.5]];
        let result = elementwise_division_2d(
            &test_kmer_counts_per_allele,
            &test_num_uniq_kmers_per_allele,
        );
        assert_eq!(result.unwrap(), expected);
    }

    #[test]
    fn test_elementwise_division_2d_zero_divisor_is_nan() {
        let counts = vec![vec![55, 11], vec![22, 10]];
        let kmers = vec![vec![10, 0], vec![2, 20]];
        let result = elementwise_division_2d(&counts, &kmers).unwrap();
        assert_eq!(result[0][0], 5.5);
        assert!(result[0][1].is_nan());
        assert_eq!(result[1][1], 0.5);
    }

    #[test]
    fn test_elementwise_division_2d_row_count_mismatch_is_err() {
        let counts = vec![vec![55, 11]];
        let kmers = vec![vec![10, 4], vec![2, 20]];
        let result = elementwise_division_2d(&counts, &kmers);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("1 lines but index has 2"));
    }

    #[test]
    fn test_elementwise_division_2d_allele_count_mismatch_is_err() {
        let counts = vec![vec![55, 11], vec![22, 10, 3]];
        let kmers = vec![vec![10, 4], vec![2, 20]];
        let result = elementwise_division_2d(&counts, &kmers);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("3 allele counts but index has 2"));
    }

    #[test]
    fn test_vec_vec_string_to_vec_vec_u32_ok() {
        let result = vec_vec_string_to_vec_vec_u32(vec![vec!["55".into(), "11".into()]]).unwrap();
        assert_eq!(result, vec![vec![55u32, 11]]);
    }

    #[test]
    fn test_vec_vec_string_to_vec_vec_u32_rejects_garbage() {
        let result = vec_vec_string_to_vec_vec_u32(vec![vec!["55".into(), "abc".into()]]);
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Invalid count 'abc'"));
    }

    #[test]
    fn test_vec_vec_string_to_vec_vec_u32_rejects_negative() {
        let result = vec_vec_string_to_vec_vec_u32(vec![vec!["-5".into()]]);
        assert!(result.is_err());
    }

    fn write_temp(dir: &std::path::Path, name: &str, content: &str) -> String {
        let path = dir.join(name);
        std::fs::write(&path, content).unwrap();
        path.to_str().unwrap().to_string()
    }

    /// Well-formed two-allele index: 2 entries, kmer-count columns 2|3 and 1|1.
    const GOOD_INDEX: &str = concat!(
        "0,1,100,AAAAA,REF|ALT,AAAAA|ACAAA,2|3,AAAAA;CAAAC|GGGGT;TTTTA;CCCAG\n",
        "1,1,200,CCCCC,REF|ALT,CCCCC|CCGGG,1|1,CCCCC|GGGGG\n",
    );
    /// Matching counts: 2 lines, 2 alleles each.
    const GOOD_COUNTS: &str = "10|0\n5|5\n";

    #[test]
    fn test_call_from_counts_happy_path() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        let counts = write_temp(dir.path(), "counts.txt", GOOD_COUNTS);
        let out = dir.path().join("freqs.txt");
        call_from_counts(&index, &counts, out.to_str().unwrap()).unwrap();
        // Line 1: 10/2=5, 0/3=0 -> freqs 5/5=1, 0/5=0. Line 2: 5/1=5, 5/1=5 -> 0.5|0.5.
        let content = std::fs::read_to_string(&out).unwrap();
        let lines: Vec<&str> = content.lines().collect();
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0], "1|0");
        assert_eq!(lines[1], "0.5|0.5");
    }

    #[test]
    fn test_call_from_counts_empty_counts_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        let counts = write_temp(dir.path(), "counts.txt", "");
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("is empty"));
        assert!(!out.exists());
    }

    #[test]
    fn test_call_from_counts_garbage_counts_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        let counts = write_temp(dir.path(), "counts.txt", "garbage line\n");
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(!out.exists());
    }

    #[test]
    fn test_call_from_counts_too_few_lines_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        let counts = write_temp(dir.path(), "counts.txt", "10|0\n");
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("1 lines but index has 2"));
    }

    #[test]
    fn test_call_from_counts_too_many_lines_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        let counts = write_temp(dir.path(), "counts.txt", "10|0\n5|5\n9|9\n");
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("3 lines but index has 2"));
    }

    #[test]
    fn test_call_from_counts_allele_mismatch_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", GOOD_INDEX);
        // Line 1 has 3 alleles but the index row has 2.
        let counts = write_temp(dir.path(), "counts.txt", "10|0|1\n5|5\n");
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(!out.exists());
    }

    #[test]
    fn test_call_from_counts_missing_counts_file() {
        let result = call_from_counts(
            "does-not-matter.txt",
            "/nonexistent/counts.txt",
            "/tmp/opencode/never.txt",
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_call_from_counts_missing_index() {
        let result = call_from_counts(
            "/nonexistent/index.txt",
            "does-not-matter.txt",
            "/tmp/opencode/never.txt",
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_call_from_counts_garbage_index_is_err_not_panic() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", "short line\n");
        let counts = write_temp(dir.path(), "counts.txt", GOOD_COUNTS);
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(!out.exists());
    }

    #[test]
    fn test_call_from_counts_empty_index_is_err() {
        let dir = tempfile::tempdir().unwrap();
        let index = write_temp(dir.path(), "index.txt", "");
        let counts = write_temp(dir.path(), "counts.txt", GOOD_COUNTS);
        let out = dir.path().join("freqs.txt");
        let result = call_from_counts(&index, &counts, out.to_str().unwrap());
        assert!(result.is_err());
        assert!(!out.exists());
    }
}
